openapi: 3.0.1
info:
    title: supreme-redirect
    description: URL redirect for Supreme Court opinions
    version: 0.0.1

paths:
    /{volume}/{page}:
      get:
        parameters:
          - name: volume
            in: path
            required: true
            schema:
              type: string
          - name: page
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "200 response"
            headers: {}
          302:
            description: "302 response"
            headers:
              Location:
                schema:
                  type: string
        x-amazon-apigateway-integration:
          uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:758881537981:function:redirect-lambda/invocations"
          responses:
            default:
              statusCode: "302"
              responseParameters:
                method.response.header.Location: "integration.response.body.location"
          passthroughBehavior: "when_no_match"
          httpMethod: "POST"
          requestTemplates:
            application/json: "{\"volume\": \"$input.params('volume')\", \"page\": \"$input.params('page')\"}"
          type: "aws"
